### ISSUE TITLE
Drop `viewModePlugin` changes

### ISSUE THREAD

**Issue by jimkang** [harvard-dce/paella#12]
Originally for "#DCE MATT-473, verify selectedProfile exists"

Code does this: If there is a next and previous button that are not the same (is that comparison of those types valid?), use the `selectedProfile` to set the `previousButton`'s class and then set the `profileName`.

[@djcp says this is probably unnecessary now.](https://github.com/jimkang/dce-4.1.1-paella-master-diffs/commit/6253d9f6febc95d80d68d8bd950b039dde277711?diff=unified#commitcomment-11978381)

**Comment by karendolan** [comment]
Can't tell without looking at the code, but at one point there was assumption of a previous profile if a new profile is selected.

**Comment by jimkang** [comment]
@djcp confirms that we do not use this plugin.

**Comment by jimkang** [comment]
It turned out [this plugin](https://github.com/harvard-dce/dce-paella-extensions/commit/016b7b18860dae268edf01d68f787abaa43cb1e5) is different from the standard mode toggle plugin and needed to be included.
